services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  app:
    image: library-app
    container_name: library-app
    ports:
      - "9090:8081"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/books
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
